### ISSUE TITLE
Chrome 分頁錄影無法下載

### ISSUE THREAD

**Issue by mathppp** [ottokang/YmlY-Screen-Recorder#1]
開啟網站 https://ottokang.github.io/YmlY-Screen-Recorder/
錄影後無法下載。

**Comment by ottokang** [comment]
麻煩請補充作業系統、使用的瀏覽器、電腦記憶體大小

如果可以的話，在發生不能下載的狀況，按下 F12 開啟瀏覽器主控台，擷取頁面或複製錯誤訊息，可以幫助除錯。

**Comment by mathppp** [comment]
OS: Windows 10 22H2
RAM: 32GB
Browser: Chrome 112.0.5615.50
![image](https://user-images.githubusercontent.com/37207323/230430440-e10700f8-75ae-47cf-a46b-be839684169f.png)

**Comment by ottokang** [comment]
感謝，能否再補充無法下載的步驟？例如選擇了什麼模式、是否有同意瀏覽器存取畫面跟麥克風，可以用其他的螢幕錄影程式復現最好

**Comment by ottokang** [comment]
已經確認問題，分頁錄影無法下載，會再找時間修復

**Comment by ottokang** [comment]
Fix in 0076006
